server:
  port: 8080

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-service:8761/eureka
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**
        - id: banned-words-service
          uri: lb://BANNED-WORDS-SERVICE
          predicates:
            - Path=/api/banned-words/**
      discovery:
        locator:
          enable: true
          lower-case-service-id: true