server:
  port: 8183
spring:
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka