server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: your-strong-secret-key
  expiration: 3600000
  refresh-expiration: 604800000