server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/users-service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost # Явное указание hostname
    instance-id: ${spring.application.name}:${server.port}
jwt:
  secret: your-strong-secret-key
  expiration: 3600000
  refresh-expiration: 604800000